/**
 * File Generated by Sideko (sideko.dev)
 */

export type ListRequest = {
  tenantId: string;
  realmId: string;
  identityId: string;
  pageSize?: number;
  pageToken?: string;
  resourceServerId?: string;
  skip?: number;
};
