/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/beyond_identity_api";

describe("init client", () => {
  test.concurrent("tests initializing client with all available auths", () => {
    // test init client (keep comment for code generation)
    new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
  });
});

// test client mehtods (keep comment for code generation)
