/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/beyond_identity_api";

// test client mehtods (keep comment for code generation)

describe("tests client.v1.tenants.realms.resourceServers.roles.listMembers.list", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response =
      await client.v1.tenants.realms.resourceServers.roles.listMembers.list({
        tenantId: "000176d94fd7b4d1",
        realmId: "19a95130480dfa79",
        resourceServerId: "84db69f5-48a8-4c11-8cda-1bae3a73f07e",
        roleId: "fb785d40cbe4fc0d",
        groupsPageSize: 123,
        groupsSkip: 123,
        identitiesPageSize: 123,
        identitiesSkip: 123,
        pageToken: "string",
      });
    console.log(response);
  });
});
