/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/beyond_identity_api";

// test client mehtods (keep comment for code generation)

describe("tests client.v1.tenants.realms.scim.v2.users.put", () => {
  test.concurrent("200 generated_success_replace_user", async () => {
    // Generated success test for Replace User body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.users.put({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      userId: "string",
      data: {
        user: {
          active: true,
          displayName: "Test User",
          emails: [{ primary: true, value: "test@test.com" }],
          externalId: "external-id-abcdef",
          id: "ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
          meta: {
            created: "2022-04-07T07:23:33.000Z",
            lastModified: "2023-03-30T07:00:14.000Z",
            location: "Groups/ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
            resourceType: "Group",
            version: "W/0",
          },
          name: { familyName: "Jensen", givenName: "Barbara" },
          schemas: ["urn:ietf:params:scim:schemas:core:2.0:User"],
          userName: "test_user",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.scim.v2.users.create", () => {
  test.concurrent("201 generated_success_create_user", async () => {
    // Generated success test for Create User body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.users.create({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      data: {
        user: {
          active: true,
          displayName: "Test User",
          emails: [{ primary: true, value: "test@test.com" }],
          externalId: "external-id-abcdef",
          id: "ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
          meta: {
            created: "2022-04-07T07:23:33.000Z",
            lastModified: "2023-03-30T07:00:14.000Z",
            location: "Groups/ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
            resourceType: "Group",
            version: "W/0",
          },
          name: { familyName: "Jensen", givenName: "Barbara" },
          schemas: ["urn:ietf:params:scim:schemas:core:2.0:User"],
          userName: "test_user",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.scim.v2.users.patch", () => {
  test.concurrent("200 generated_success_update_display_name", async () => {
    // Generated success test for Update Display Name body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.users.patch({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      userId: "string",
      data: {
        user: {
          active: true,
          displayName: "Test User",
          emails: [{ primary: true, value: "test@test.com" }],
          externalId: "external-id-abcdef",
          id: "ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
          meta: {
            created: "2022-04-07T07:23:33.000Z",
            lastModified: "2023-03-30T07:00:14.000Z",
            location: "Groups/ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
            resourceType: "Group",
            version: "W/0",
          },
          name: { familyName: "Jensen", givenName: "Barbara" },
          schemas: ["urn:ietf:params:scim:schemas:core:2.0:User"],
          userName: "test_user",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.scim.v2.users.get", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.users.get({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      userId: "string",
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.scim.v2.users.list", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.users.list({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      count: 123,
      filter: "string",
      startIndex: 123,
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.scim.v2.users.delete", () => {
  test.concurrent("204 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.users.delete({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      userId: "string",
    });
    console.log(response);
  });
});
