/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/beyond_identity_api";

// test client mehtods (keep comment for code generation)

describe("tests client.v1.tenants.realms.groups.create", () => {
  test.concurrent("200 generated_success_create_group", async () => {
    // Generated success test for Create Group body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.groups.create({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      data: {
        group: {
          create_time: "2022-03-14T03:42:52.905Z",
          description: "A group of realm administrators.",
          display_name: "Realm Administrators",
          id: "81490afab171aef0",
          realm_id: "7df92e4a38ba0993",
          tenant_id: "0001b42d80372976",
          update_time: "2022-06-14T05:55:23.823Z",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.groups.patch", () => {
  test.concurrent("200 generated_success_update_display_name", async () => {
    // Generated success test for Update Display Name body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.groups.patch({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      groupId: "81490afab171aef0",
      data: {
        group: {
          create_time: "2022-03-14T03:42:52.905Z",
          description: "A group of realm administrators.",
          display_name: "Realm Administrators",
          id: "81490afab171aef0",
          realm_id: "7df92e4a38ba0993",
          tenant_id: "0001b42d80372976",
          update_time: "2022-06-14T05:55:23.823Z",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.groups.get", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.groups.get({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      groupId: "81490afab171aef0",
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.groups.list", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.groups.list({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      pageSize: 123,
      pageToken: "string",
      skip: 123,
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.groups.delete", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.groups.delete({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      groupId: "81490afab171aef0",
    });
    console.log(response);
  });
});
