/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/beyond_identity_api";

// test client mehtods (keep comment for code generation)

describe("tests client.v1.tenants.realms.scim.v2.groups.create", () => {
  test.concurrent("201 generated_success_create_group", async () => {
    // Generated success test for Create Group body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.groups.create({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      data: {
        group: {
          displayName: "Help Desk",
          id: "ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
          meta: {
            created: "2022-04-07T07:23:33.000Z",
            lastModified: "2023-03-30T07:00:14.000Z",
            location: "Groups/ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
            resourceType: "Group",
            version: "W/0",
          },
          schemas: ["urn:ietf:params:scim:schemas:core:2.0:Group"],
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.scim.v2.groups.patch", () => {
  test.concurrent("200 generated_success_add_members", async () => {
    // Generated success test for Add Members body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.groups.patch({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      groupId: "string",
      data: {
        group: {
          displayName: "Help Desk",
          id: "ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
          meta: {
            created: "2022-04-07T07:23:33.000Z",
            lastModified: "2023-03-30T07:00:14.000Z",
            location: "Groups/ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
            resourceType: "Group",
            version: "W/0",
          },
          schemas: ["urn:ietf:params:scim:schemas:core:2.0:Group"],
        },
      },
    });
    console.log(response);
  });
  test.concurrent("200 generated_success_remove_member", async () => {
    // Generated success test for Remove Member body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.groups.patch({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      groupId: "string",
      data: {
        group: {
          displayName: "Help Desk",
          id: "ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
          meta: {
            created: "2022-04-07T07:23:33.000Z",
            lastModified: "2023-03-30T07:00:14.000Z",
            location: "Groups/ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
            resourceType: "Group",
            version: "W/0",
          },
          schemas: ["urn:ietf:params:scim:schemas:core:2.0:Group"],
        },
      },
    });
    console.log(response);
  });
  test.concurrent("200 generated_success_replace_display_name", async () => {
    // Generated success test for Replace DisplayName body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.groups.patch({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      groupId: "string",
      data: {
        group: {
          displayName: "Help Desk",
          id: "ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
          meta: {
            created: "2022-04-07T07:23:33.000Z",
            lastModified: "2023-03-30T07:00:14.000Z",
            location: "Groups/ed9fcce6-ec82-458e-ae58-e2d975cfc32d",
            resourceType: "Group",
            version: "W/0",
          },
          schemas: ["urn:ietf:params:scim:schemas:core:2.0:Group"],
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.scim.v2.groups.get", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.groups.get({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      groupId: "string",
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.scim.v2.groups.list", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.groups.list({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      count: 123,
      filter: "string",
      startIndex: 123,
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.scim.v2.groups.delete", () => {
  test.concurrent("204 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.scim.v2.groups.delete({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      groupId: "string",
    });
    console.log(response);
  });
});
