/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/beyond_identity_api";

// test client mehtods (keep comment for code generation)

describe("tests client.v1.tenants.patch", () => {
  test.concurrent("200 generated_success_update_display_name", async () => {
    // Generated success test for Update Display Name body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.patch({
      tenantId: "000176d94fd7b4d1",
      data: {
        tenant: {
          create_time: "2022-01-28T12:00:02.423Z",
          display_name: "Test Tenant",
          id: "000176d94fd7b4d1",
          update_time: "2022-04-19T15:17:21.186Z",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.get", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.get({
      tenantId: "000176d94fd7b4d1",
    });
    console.log(response);
  });
});
