/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/beyond_identity_api";

// test client mehtods (keep comment for code generation)

describe("tests client.v1.tenants.realms.applications.tokens.list", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.applications.tokens.list({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      applicationId: "38833c36-6f47-4992-9329-ea0a00915137",
      principalId: "string",
      principalType: "string",
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.applications.tokens.delete", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.applications.tokens.delete({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      applicationId: "38833c36-6f47-4992-9329-ea0a00915137",
      tokenId: "string",
    });
    console.log(response);
  });
});
