/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/beyond_identity_api";

// test client mehtods (keep comment for code generation)

describe("tests client.v1.tenants.realms.resourceServers.roles.create", () => {
  test.concurrent("200 generated_success_create_role", async () => {
    // Generated success test for Create Role body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response =
      await client.v1.tenants.realms.resourceServers.roles.create({
        tenantId: "000176d94fd7b4d1",
        realmId: "19a95130480dfa79",
        resourceServerId: "84db69f5-48a8-4c11-8cda-1bae3a73f07e",
        data: {
          group: {
            create_time: "2023-02-14T18:18:58.332Z",
            description: "Customer support personnel.",
            display_name: "Help Desk",
            id: "fb785d40cbe4fc0d",
            realm_id: "bb26e0e8ecdef843",
            resource_server_id: "7b5a4325-00e0-4379-bd7b-3e5e7e30b09e",
            tenant_id: "00010036778ce59f",
            update_time: "2023-02-14T18:18:58.332Z",
          },
        },
      });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.resourceServers.roles.patch", () => {
  test.concurrent("200 generated_success_update_display_name", async () => {
    // Generated success test for Update Display Name body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.resourceServers.roles.patch(
      {
        tenantId: "000176d94fd7b4d1",
        realmId: "19a95130480dfa79",
        resourceServerId: "84db69f5-48a8-4c11-8cda-1bae3a73f07e",
        roleId: "fb785d40cbe4fc0d",
        data: {
          role: {
            create_time: "2023-02-14T18:18:58.332Z",
            description: "Customer support personnel.",
            display_name: "Help Desk",
            id: "fb785d40cbe4fc0d",
            realm_id: "bb26e0e8ecdef843",
            resource_server_id: "7b5a4325-00e0-4379-bd7b-3e5e7e30b09e",
            tenant_id: "00010036778ce59f",
            update_time: "2023-02-14T18:18:58.332Z",
          },
        },
      },
    );
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.resourceServers.roles.get", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.resourceServers.roles.get({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      resourceServerId: "84db69f5-48a8-4c11-8cda-1bae3a73f07e",
      roleId: "fb785d40cbe4fc0d",
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.resourceServers.roles.list", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.resourceServers.roles.list({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      resourceServerId: "84db69f5-48a8-4c11-8cda-1bae3a73f07e",
      pageSize: 123,
      pageToken: "string",
      skip: 123,
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.resourceServers.roles.delete", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response =
      await client.v1.tenants.realms.resourceServers.roles.delete({
        tenantId: "000176d94fd7b4d1",
        realmId: "19a95130480dfa79",
        resourceServerId: "84db69f5-48a8-4c11-8cda-1bae3a73f07e",
        roleId: "fb785d40cbe4fc0d",
      });
    console.log(response);
  });
});
