/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/beyond_identity_api";

// test client mehtods (keep comment for code generation)

describe("tests client.v1.tenants.realms.themes.create", () => {
  test.concurrent("200 generated_success_create_theme", async () => {
    // Generated success test for Create Theme body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.themes.create({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      data: {
        theme: {
          button_color: "#4673D3",
          button_text_color: "#FFFFFF",
          create_time: "2022-07-28T18:00:00.000Z",
          email_realm_name: "Realm Administrators",
          id: "88ef08fb-c3f9-44e2-b174-fbb239e1dc47",
          logo_url_dark: "https://example.com/logo_url_dark.png",
          logo_url_light: "https://example.com/logo_url_light.png",
          realm_id: "7df92e4a38ba0993",
          support_url: "https://example.com/support",
          tenant_id: "0001b42d80372976",
          update_time: "2022-07-30T16:00:00.000Z",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.themes.patch", () => {
  test.concurrent("200 generated_success_update_email_realm_name", async () => {
    // Generated success test for Update Email Realm Name body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.themes.patch({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      themeId: "88ef08fb-c3f9-44e2-b174-fbb239e1dc47",
      data: {
        theme: {
          button_color: "#4673D3",
          button_text_color: "#FFFFFF",
          create_time: "2022-07-28T18:00:00.000Z",
          email_realm_name: "Realm Administrators",
          id: "88ef08fb-c3f9-44e2-b174-fbb239e1dc47",
          logo_url_dark: "https://example.com/logo_url_dark.png",
          logo_url_light: "https://example.com/logo_url_light.png",
          realm_id: "7df92e4a38ba0993",
          support_url: "https://example.com/support",
          tenant_id: "0001b42d80372976",
          update_time: "2022-07-30T16:00:00.000Z",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.themes.get", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.themes.get({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      themeId: "88ef08fb-c3f9-44e2-b174-fbb239e1dc47",
    });
    console.log(response);
  });
});
