/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/beyond_identity_api";

// test client mehtods (keep comment for code generation)

describe("tests client.v1.tenants.realms.resourceServers.create", () => {
  test.concurrent("200 generated_success_create_resource_server", async () => {
    // Generated success test for Create Resource Server body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.resourceServers.create({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      data: {
        resource_server: {
          display_name: "Pet API",
          id: "84db69f5-48a8-4c11-8cda-1bae3a73f07e",
          identifier: "https://api.mypetapp.com",
          is_managed: false,
          realm_id: "caf2ff640497591a",
          scopes: ["pets:read", "pets:write"],
          tenant_id: "00011f1183c67b69",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.resourceServers.patch", () => {
  test.concurrent("200 generated_success_update_display_name", async () => {
    // Generated success test for Update Display Name body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.resourceServers.patch({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      resourceServerId: "84db69f5-48a8-4c11-8cda-1bae3a73f07e",
      data: {
        resource_server: {
          display_name: "Pet API",
          id: "84db69f5-48a8-4c11-8cda-1bae3a73f07e",
          identifier: "https://api.mypetapp.com",
          is_managed: false,
          realm_id: "caf2ff640497591a",
          scopes: ["pets:read"],
          tenant_id: "00011f1183c67b69",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.resourceServers.get", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.resourceServers.get({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      resourceServerId: "84db69f5-48a8-4c11-8cda-1bae3a73f07e",
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.resourceServers.list", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.resourceServers.list({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      pageSize: 123,
      pageToken: "string",
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.resourceServers.delete", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.resourceServers.delete({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      resourceServerId: "84db69f5-48a8-4c11-8cda-1bae3a73f07e",
    });
    console.log(response);
  });
});
