/**
 * File Generated by Sideko (sideko.dev)
 */
import Client from "@public/beyond_identity_api";

// test client mehtods (keep comment for code generation)

describe("tests client.v1.tenants.realms.create", () => {
  test.concurrent("200 generated_success_default", async () => {
    // Generated success test for Default body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.create({
      tenantId: "000176d94fd7b4d1",
      data: {
        realm: {
          create_time: "2022-05-18T18:00:01.167Z",
          display_name: "Test Realm",
          id: "19a95130480dfa79",
          tenant_id: "0001f1f460b1ace6",
          update_time: "2022-05-19T14:23:01.327Z",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.patch", () => {
  test.concurrent("200 generated_success_update_display_name", async () => {
    // Generated success test for Update Display Name body example from OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.patch({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
      data: {
        realm: {
          create_time: "2022-05-18T18:00:01.167Z",
          display_name: "Test Realm",
          id: "19a95130480dfa79",
          tenant_id: "0001f1f460b1ace6",
          update_time: "2022-05-19T14:23:01.327Z",
        },
      },
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.get", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.get({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.list", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.list({
      tenantId: "000176d94fd7b4d1",
      pageSize: 123,
      pageToken: "string",
      skip: 123,
    });
    console.log(response);
  });
});

describe("tests client.v1.tenants.realms.delete", () => {
  test.concurrent("200 generated_success", async () => {
    // Generated success test based on examples in OpenAPI
    const client = new Client({
      token: "API_TOKEN",
      baseUrl: "https://api.sideko.dev/v1/mock/public/beyond-identity/1.7.0",
    });
    const response = await client.v1.tenants.realms.delete({
      tenantId: "000176d94fd7b4d1",
      realmId: "19a95130480dfa79",
    });
    console.log(response);
  });
});
