/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "@public/beyond_identity_api/types";

export type GetRequest = {
  tenantId: string;
};

export type PatchRequest = {
  tenantId: string;
  data: types.PatchV1TenantsTenantIdBody;
};
