/**
 * File Generated by Sideko (sideko.dev)
 */

export type ListRequest = {
  tenantId: string;
  realmId: string;
  identityId: string;
  pageSize?: number;
  pageToken?: string;
  skip?: number;
};

export type GetRequest = {
  tenantId: string;
  realmId: string;
  identityId: string;
  credentialId: string;
};
