/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
} from "@public/beyond_identity_api/core";
import { V2Client } from "@public/beyond_identity_api/resources/v1/tenants/realms/scim/v2";

export class ScimClient extends CoreResourceClient {
  // register resources (keep comment for code generation)
  v2: V2Client;

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
    this.v2 = new V2Client(this._client);
  }

  // register api methods (keep comment for code generation)
}
