/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "@public/beyond_identity_api/types";

export type DeleteRequest = {
  tenantId: string;
  realmId: string;
  applicationId: string;
};

export type ListRequest = {
  tenantId: string;
  realmId: string;
  pageSize?: number;
  pageToken?: string;
};

export type GetRequest = {
  tenantId: string;
  realmId: string;
  applicationId: string;
};

export type PatchRequest = {
  tenantId: string;
  realmId: string;
  applicationId: string;
  data: types.PatchV1TenantsTenantIdRealmsRealmIdApplicationsApplicationIdBody;
};

export type CreateRequest = {
  tenantId: string;
  realmId: string;
  data: types.PostV1TenantsTenantIdRealmsRealmIdApplicationsBody;
};
