/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "@public/beyond_identity_api/types";

export type DeleteRequest = {
  tenantId: string;
  realmId: string;
  authenticatorConfigId: string;
};

export type ListRequest = {
  tenantId: string;
  realmId: string;
  pageSize?: number;
  pageToken?: string;
};

export type GetRequest = {
  tenantId: string;
  realmId: string;
  authenticatorConfigId: string;
};

export type PatchRequest = {
  tenantId: string;
  realmId: string;
  authenticatorConfigId: string;
  data: types.PatchV1TenantsTenantIdRealmsRealmIdAuthenticatorConfigsAuthenticatorConfigIdBody;
};

export type CreateRequest = {
  tenantId: string;
  realmId: string;
  data: types.PostV1TenantsTenantIdRealmsRealmIdAuthenticatorConfigsBody;
};
