/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type AuthenticatorConfig = {
  config?: types.Obj01 | types.Obj11;
  display_name?: string;
  id?: string;
  realm_id?: string;
  tenant_id?: string;
};
