/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type Credential = {
  create_time?: string;
  csr_type?: types.CredentialCsrTypeEnum;
  id?: string;
  identity_id?: string;
  jwk_json?: string;
  jwk_thumbprint?: string;
  realm_id?: string;
  state?: types.CredentialStateEnum;
  tenant_id?: string;
  update_time?: string;
};
