/**
 * File Generated by Sideko (sideko.dev)
 */

export enum CredentialBindingJobStateEnum {
  Complete = "COMPLETE",
  LinkOpened = "LINK_OPENED",
  LinkSent = "LINK_SENT",
  RequestDelivered = "REQUEST_DELIVERED",
}
