/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type Error = {
  code: string;
  details?: types.ErrorDetail[];
  message: string;
};
