/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type GetV1TenantsTenantIdRealmsRealmIdApplicationsApplicationIdTokensResponse =
  {
    next_page_token?: string;
    tokens: types.GetV1TenantsTenantIdRealmsRealmIdApplicationsApplicationIdTokensResponseTokensItem[];
    total_size: number;
  };
