/**
 * File Generated by Sideko (sideko.dev)
 */

export type GetV1TenantsTenantIdRealmsRealmIdApplicationsApplicationIdTokensResponseTokensItem =
  {
    display_name?: string;
    expires?: number;
    id?: string;
    issued_at?: number;
    scopes?: string[];
    token_format?: string;
    token_suffix?: string;
    token_type?: string;
  };
