/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type Identity = {
  create_time?: string;
  display_name?: string;
  id?: string;
  realm_id?: string;
  status?: string;
  tenant_id?: string;
  traits?: types.TraitsV0;
  update_time?: string;
};
