/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ListGroupRolesResponse = {
  next_page_token?: string;
  roles: types.Role[];
  total_size: number;
};
