/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ListResourceServersResponse = {
  next_page_token?: string;
  resource_servers: types.ResourceServer[];
  total_size: number;
};
