/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ListRolesResponse = {
  groups?: types.Role[];
  next_page_token?: string;
  total_size: number;
};
