/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ListRoleMembersResponse = {
  groups: types.Group[];
  identities: types.Identity[];
  next_page_token?: string;
  total_groups_size: number;
  total_identities_size: number;
};
