/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ListGroupsResponse = {
  groups: types.Group[];
  next_page_token?: string;
  total_size: number;
};
