/**
 * File Generated by Sideko (sideko.dev)
 */

export enum Obj0AuthenticationMethodsItemTypeEnum {
  EmailOneTimePassword = "email_one_time_password",
  SoftwarePasskey = "software_passkey",
  WebauthnPasskey = "webauthn_passkey",
}
