/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type Obj0AuthenticationMethodsItem = {
  type: types.Obj0AuthenticationMethodsItemTypeEnum;
};
