/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type Obj01 = {
  authentication_methods?: types.Obj0AuthenticationMethodsItem[];
  invocation_type?: types.Obj0InvocationTypeEnum;
  invoke_url: string;
  trusted_origins: string[];
  type: types.Obj0TypeEnum1;
};
