/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type Obj11 = {
  authentication_methods: string[];
  trusted_origins: string[];
  type: types.Obj1TypeEnum1;
};
