/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type PatchV1TenantsTenantIdRealmsRealmIdAuthenticatorConfigsAuthenticatorConfigIdBody =
  {
    authenticator_config: types.AuthenticatorConfig;
  };
