/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type PatchV1TenantsTenantIdRealmsRealmIdGroupsGroupIdBody = {
  group: types.Group;
};
