/**
 * File Generated by Sideko (sideko.dev)
 */

export type PostV1TenantsTenantIdRealmsRealmIdResourceServersResourceServerIdRolesRoleIdAddMembersBody =
  {
    group_ids?: string[];
    identity_ids?: string[];
  };
