/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type PostV1TenantsTenantIdRealmsRealmIdIdentitiesIdentityIdCredentialBindingJobsResponse =
  {
    credential_binding_job: types.CredentialBindingJob;
    credential_binding_link?: string;
  };
