/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type PutV1TenantsTenantIdRealmsRealmIdScimV2UsersUserIdBody = {
  user: types.ScimUser;
};
