/**
 * File Generated by Sideko (sideko.dev)
 */

export type ResourceServer = {
  display_name?: string;
  id?: string;
  identifier?: string;
  is_managed?: boolean;
  realm_id?: string;
  scopes?: string[];
  tenant_id?: string;
};
