/**
 * File Generated by Sideko (sideko.dev)
 */

export type Role = {
  create_time?: string;
  description?: string;
  display_name?: string;
  id?: string;
  realm_id?: string;
  resource_server_id?: string;
  tenant_id?: string;
  update_time?: string;
};
