/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ScimResourceType = {
  description: string;
  endpoint: string;
  id: string;
  name: string;
  schema: string;
  schemaExtensions: types.ScimResourceTypeSchemaExtensionsItem[];
  schemas: string[];
};
