/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ScimServiceProviderConfigAuthenticationSchemesItem = {
  description?: string;
  documentationUri?: string;
  name?: string;
  specUri?: string;
  type?: types.ScimServiceProviderConfigAuthenticationSchemesItemTypeEnum;
};
