/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ScimServiceProviderConfig = {
  authenticationSchemes: types.ScimServiceProviderConfigAuthenticationSchemesItem[];
  bulk: types.ScimServiceProviderConfigBulk;
  changePassword: types.ScimServiceProviderConfigChangePassword;
  documentationUri: string;
  etag: types.ScimServiceProviderConfigEtag;
  filter: types.ScimServiceProviderConfigFilter;
  patch: types.ScimServiceProviderConfigPatch;
  schemas: string[];
  sort: types.ScimServiceProviderConfigSort;
};
