/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ScimSchema = {
  attributes: types.ScimSchemaAttributesItem[];
  description: string;
  id: string;
  name: string;
};
