/**
 * File Generated by Sideko (sideko.dev)
 */

export enum ScimServiceProviderConfigAuthenticationSchemesItemTypeEnum {
  Httpbasic = "httpbasic",
  Httpdigest = "httpdigest",
  Oauth = "oauth",
  Oauth2 = "oauth2",
  Oauthbearertoken = "oauthbearertoken",
}
