/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ScimUser = {
  active?: boolean;
  displayName?: string;
  emails?: types.ScimUserEmailsItem[];
  externalId?: string;
  id?: string;
  meta?: types.ScimUserMeta;
  name?: types.ScimUserName;
  schemas: string[];
  userName?: string;
};
