/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ScimSchemaAttributesItem = {
  caseExact?: boolean;
  description: string;
  multiValued: boolean;
  mutability: types.ScimSchemaAttributesItemMutabilityEnum;
  name: string;
  referenceTypes?: string[];
  required: boolean;
  returned: types.ScimSchemaAttributesItemReturnedEnum;
  subAttributes?: Record<string, any>[];
  type: types.ScimSchemaAttributesItemTypeEnum;
  uniqueness?: types.ScimSchemaAttributesItemUniquenessEnum;
};
