/**
 * File Generated by Sideko (sideko.dev)
 */

export enum ScimSchemaAttributesItemTypeEnum {
  Boolean = "boolean",
  Complex = "complex",
  DateTime = "dateTime",
  Decimal = "decimal",
  Integer = "integer",
  Reference = "reference",
  String = "string",
}
