/**
 * File Generated by Sideko (sideko.dev)
 */

export enum ScimSchemaAttributesItemMutabilityEnum {
  Immutable = "immutable",
  ReadOnly = "readOnly",
  ReadWrite = "readWrite",
  WriteOnly = "writeOnly",
}
