/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type ScimGroup = {
  displayName?: string;
  id?: string;
  meta?: types.ScimGroupMeta;
  schemas: string[];
};
