/**
 * File Generated by Sideko (sideko.dev)
 */

export type Theme = {
  button_color?: string;
  button_text_color?: string;
  create_time?: string;
  email_realm_name?: string;
  id?: string;
  logo_url_dark?: string;
  logo_url_light?: string;
  realm_id?: string;
  support_url?: string;
  tenant_id?: string;
  update_time?: string;
};
