/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "@public/beyond_identity_api/types";

export type TokenConfiguration = {
  expires_after: number;
  subject_field?: types.TokenConfigurationSubjectFieldEnum;
  token_signing_algorithm?: types.TokenConfigurationTokenSigningAlgorithmEnum;
};
