/**
 * File Generated by Sideko (sideko.dev)
 */

export type TraitsV0 = {
  external_id?: string;
  family_name?: string;
  given_name?: string;
  primary_email_address?: string;
  type: string;
  username?: string;
};
