/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "@public/beyond_identity_api/types";

export type CreateRequest = {
  tenantId: string;
  realmId: string;
  groupId: string;
  data: types.PostV1TenantsTenantIdRealmsRealmIdGroupsGroupIdAddMembersBody;
};
