/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "@public/beyond_identity_api/types";

export type ListRequest = {
  tenantId: string;
  realmId: string;
  identityId: string;
  pageSize?: number;
  pageToken?: string;
  skip?: number;
};

export type GetRequest = {
  tenantId: string;
  realmId: string;
  identityId: string;
  credentialBindingJobId: string;
};

export type CreateRequest = {
  tenantId: string;
  realmId: string;
  identityId: string;
  data: types.PostV1TenantsTenantIdRealmsRealmIdIdentitiesIdentityIdCredentialBindingJobsBody;
};
