/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "@public/beyond_identity_api/core";
import * as requests from "@public/beyond_identity_api/resources/v1/tenants/realms/scim/v2/groups/request-types";
import * as types from "@public/beyond_identity_api/types";
import qs from "qs";

export class GroupsClient extends CoreResourceClient {
  // register resources (keep comment for code generation)

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
  }

  // register api methods (keep comment for code generation)

  /**
   * To create a group, send a POST request to `/Groups`. Values in the request body for read-only fields will be ignored.
   *
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.ScimGroup> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "post",
      path: `/v1/tenants/${request.tenantId}/realms/${request.realmId}/scim/v2/Groups/`,
      auth: ["BearerAuth"],
      contentType: "application/json",
      body: request.data,
      responseType: "json",
      opts,
    });
  }

  /**
   * To update only specific attributes of an existing group, send a PATCH
   * request to `/Groups/$GROUP_ID`. Values in the request body for immutable or
   * read-only fields will be ignored. Fields that are omitted from the request
   * body will be left unchanged.
   *
   * Note that the Beyond Identity SCIM server currently does not support atomic
   * PATCH operations. If a request contains multiple operations, the request
   * may be partially applied.
   *
   * The Beyond Identity SCIM server also does not support modifying both a
   * group and its membership in the same operation. For example, a PATCH
   * request to update a group's display name and its membership should specify
   * two separate operations, one to update the display name and the other to
   * modify the membership.
   *
   * Currently, "replace" operations are supported for displayName while "add"
   * and "remove" operations are supported for members. Multiple members may be
   * added at a time, but batch remove is not supported. Note that while member
   * changes will take affect, they will not be reflected in the response
   * as members are not currently returned with groups.
   *
   */
  patch(
    request: requests.PatchRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.ScimGroup> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "patch",
      path: `/v1/tenants/${request.tenantId}/realms/${request.realmId}/scim/v2/Groups/${request.groupId}`,
      auth: ["BearerAuth"],
      contentType: "application/json",
      body: request.data,
      responseType: "json",
      opts,
    });
  }

  /**
   * To retrieve an existing group, send a GET request to `/Groups/$GROUP_ID`.
   *
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.ScimGroup> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "get",
      path: `/v1/tenants/${request.tenantId}/realms/${request.realmId}/scim/v2/Groups/${request.groupId}`,
      auth: ["BearerAuth"],
      responseType: "json",
      opts,
    });
  }

  /**
   * To list all groups, send a GET request to `/Groups`.
   *
   * Currently, filtering on groups only supports the `eq` and `ne` operators
   * and the `displayName` attribute.
   *
   * The response will contain at most 1000 items. If count is not specified or
   * is zero, the response will not contain any resources. There is no defined
   * ordering of the list of groups in the response. Note that the maximum page
   * size is subject to change.
   *
   * Members will not be returned with the group.
   *
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.GetV1TenantsTenantIdRealmsRealmIdScimV2GroupsResponse> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "get",
      path: `/v1/tenants/${request.tenantId}/realms/${request.realmId}/scim/v2/Groups/`,
      auth: ["BearerAuth"],
      query: [
        qs.stringify({ count: request.count }),
        qs.stringify({ filter: request.filter }),
        qs.stringify({ startIndex: request.startIndex }),
      ],
      responseType: "json",
      opts,
    });
  }

  /**
   * To delete a group, send a DELETE request to `/Groups/$GROUP_ID`.
   *
   */
  delete(
    request: requests.DeleteRequest,
    opts?: RequestOptions,
  ): ApiPromise<null> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "delete",
      path: `/v1/tenants/${request.tenantId}/realms/${request.realmId}/scim/v2/Groups/${request.groupId}`,
      auth: ["BearerAuth"],
      responseType: "json",
      opts,
    });
  }
}
