/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "@public/beyond_identity_api/types";

export type DeleteRequest = {
  tenantId: string;
  realmId: string;
  userId: string;
};

export type ListRequest = {
  tenantId: string;
  realmId: string;
  count?: number;
  filter?: string;
  startIndex?: number;
};

export type GetRequest = {
  tenantId: string;
  realmId: string;
  userId: string;
};

export type PatchRequest = {
  tenantId: string;
  realmId: string;
  userId: string;
  data: types.PatchV1TenantsTenantIdRealmsRealmIdScimV2UsersUserIdBody;
};

export type CreateRequest = {
  tenantId: string;
  realmId: string;
  data: types.PostV1TenantsTenantIdRealmsRealmIdScimV2UsersBody;
};

export type PutRequest = {
  tenantId: string;
  realmId: string;
  userId: string;
  data: types.PutV1TenantsTenantIdRealmsRealmIdScimV2UsersUserIdBody;
};
