/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "@public/beyond_identity_api/types";

export type DeleteRequest = {
  tenantId: string;
  realmId: string;
};

export type ListRequest = {
  tenantId: string;
  pageSize?: number;
  pageToken?: string;
  skip?: number;
};

export type GetRequest = {
  tenantId: string;
  realmId: string;
};

export type PatchRequest = {
  tenantId: string;
  realmId: string;
  data: types.PatchV1TenantsTenantIdRealmsRealmIdBody;
};

export type CreateRequest = {
  tenantId: string;
  data: types.PostV1TenantsTenantIdRealmsBody;
};
