/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "@public/beyond_identity_api/core";
import { ApplicationsClient } from "@public/beyond_identity_api/resources/v1/tenants/realms/applications";
import { AuthenticatorConfigsClient } from "@public/beyond_identity_api/resources/v1/tenants/realms/authenticator-configs";
import { GroupsClient } from "@public/beyond_identity_api/resources/v1/tenants/realms/groups";
import { IdentitiesClient } from "@public/beyond_identity_api/resources/v1/tenants/realms/identities";
import { ResourceServersClient } from "@public/beyond_identity_api/resources/v1/tenants/realms/resource-servers";
import { ScimClient } from "@public/beyond_identity_api/resources/v1/tenants/realms/scim";
import { ThemesClient } from "@public/beyond_identity_api/resources/v1/tenants/realms/themes";
import * as requests from "@public/beyond_identity_api/resources/v1/tenants/realms/request-types";
import * as types from "@public/beyond_identity_api/types";
import qs from "qs";

export class RealmsClient extends CoreResourceClient {
  // register resources (keep comment for code generation)
  applications: ApplicationsClient;
  authenticatorConfigs: AuthenticatorConfigsClient;
  groups: GroupsClient;
  identities: IdentitiesClient;
  resourceServers: ResourceServersClient;
  scim: ScimClient;
  themes: ThemesClient;

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
    this.applications = new ApplicationsClient(this._client);
    this.authenticatorConfigs = new AuthenticatorConfigsClient(this._client);
    this.groups = new GroupsClient(this._client);
    this.identities = new IdentitiesClient(this._client);
    this.resourceServers = new ResourceServersClient(this._client);
    this.scim = new ScimClient(this._client);
    this.themes = new ThemesClient(this._client);
  }

  // register api methods (keep comment for code generation)

  /**
   * To create a realm, send a POST request to `/v1/tenants/$TENANT_ID/realms`. Values in the request body for read-only fields will be ignored.
   *
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.Realm> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "post",
      path: `/v1/tenants/${request.tenantId}/realms`,
      auth: ["BearerAuth"],
      contentType: "application/json",
      body: request.data,
      responseType: "json",
      opts,
    });
  }

  /**
   * To update only specific attributes of an existing realm, send a PATCH request to `/v1/tenants/$TENANT_ID/realms/$REALM_ID`. Values in the request body for immutable or read-only fields will be ignored. Fields that are omitted from the request body will be left unchanged.
   *
   */
  patch(
    request: requests.PatchRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.Realm> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "patch",
      path: `/v1/tenants/${request.tenantId}/realms/${request.realmId}`,
      auth: ["BearerAuth"],
      contentType: "application/json",
      body: request.data,
      responseType: "json",
      opts,
    });
  }

  /**
   * To retrieve an existing realm, send a GET request to `/v1/tenants/$TENANT_ID/realms/$REALM_ID`.
   *
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.Realm> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "get",
      path: `/v1/tenants/${request.tenantId}/realms/${request.realmId}`,
      auth: ["BearerAuth"],
      responseType: "json",
      opts,
    });
  }

  /**
   * To list all realms for a tenant, send a GET request to
   * `/v1/tenants/$TENANT_ID/realms`.
   *
   * The response will contain at most 200 items and may contain a page token to
   * query the remaining items. If page size is not specified, the response will
   * contain 20 items. There is no defined ordering of the list of realms in the
   * response. Note that the maximum and default page sizes are subject to
   * change.
   *
   * When paginating, the page size is maintained by the page token but may be
   * overridden on subsequent requests. The skip is not maintained by the page
   * token and must be specified on each subsequent request.
   *
   * Page tokens expire after one week. Requests which specify an expired page
   * token will result in undefined behavior.
   *
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.ListRealmsResponse> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "get",
      path: `/v1/tenants/${request.tenantId}/realms`,
      auth: ["BearerAuth"],
      query: [
        qs.stringify({ page_size: request.pageSize }),
        qs.stringify({ page_token: request.pageToken }),
        qs.stringify({ skip: request.skip }),
      ],
      responseType: "json",
      opts,
    });
  }

  /**
   * To delete a realm, send a DELETE request to `/v1/tenants/$TENANT_ID/realms/$REALM_ID`. To be deleted, a realm must not have any identities, groups, or roles. All associated resources must first be deleted or you will receive a 409 error.
   * A successful request will receive a 200 status code with no body in the response. This indicates that the request was processed successfully.
   *
   */
  delete(
    request: requests.DeleteRequest,
    opts?: RequestOptions,
  ): ApiPromise<null> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "delete",
      path: `/v1/tenants/${request.tenantId}/realms/${request.realmId}`,
      auth: ["BearerAuth"],
      responseType: "json",
      opts,
    });
  }
}
