/**
 * File Generated by Sideko (sideko.dev)
 */

export type ListRequest = {
  tenantId: string;
  realmId: string;
  resourceServerId: string;
  roleId: string;
  groupsPageSize?: number;
  groupsSkip?: number;
  identitiesPageSize?: number;
  identitiesSkip?: number;
  pageToken?: string;
};
