/**
 * File Generated by Sideko (sideko.dev)
 */

export type DeleteRequest = {
  tenantId: string;
  realmId: string;
  applicationId: string;
  tokenId: string;
};

export type ListRequest = {
  tenantId: string;
  realmId: string;
  applicationId: string;
  principalId?: string;
  principalType?: string;
};
