/**
 * File Generated by Sideko (sideko.dev)
 */
import { CoreClient, AuthBearer } from "@public/beyond_identity_api/core";
import { Environment } from "@public/beyond_identity_api/environment";
import { V1Client } from "@public/beyond_identity_api/resources/v1";

export interface ClientOptions {
  baseUrl?: string;
  environment?: Environment;
  timeout?: number;
  token?: string;
}

export class Client {
  protected _client: CoreClient;
  // register resources (keep comment for code generation)
  v1: V1Client;

  constructor(opts?: ClientOptions) {
    const baseUrl = opts?.baseUrl
      ? opts?.baseUrl
      : opts?.environment ?? Environment.Default;
    this._client = new CoreClient({ baseUrl, timeout: opts?.timeout });

    // register auth methods (keep comment for code generation)
    this._client.registerAuth("BearerAuth", new AuthBearer(opts?.token));

    // init resources (keep comment for code generation)
    this.v1 = new V1Client(this._client);
  }

  // register api methods (keep comment for code generation)
}
