/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "@public/beyond_identity_api/core";
import * as requests from "@public/beyond_identity_api/resources/v1/tenants/realms/scim/v2/service-provider-config/request-types";
import * as types from "@public/beyond_identity_api/types";

export class ServiceProviderConfigClient extends CoreResourceClient {
  // register resources (keep comment for code generation)

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
  }

  // register api methods (keep comment for code generation)

  /**
   * To retrieve the service provider configuration, send a GET request to `/ServiceProviderConfig`.
   *
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.ScimServiceProviderConfig> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "get",
      path: `/v1/tenants/${request.tenantId}/realms/${request.realmId}/scim/v2/ServiceProviderConfig`,
      auth: ["BearerAuth"],
      responseType: "json",
      opts,
    });
  }
}
